# Generated by Django 4.2.5 on 2023-10-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='id',
            field=models.UUIDField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
